### ISSUE TITLE
Only MetaMask wallet is supported 

### ISSUE THREAD

**Issue by polymorpher** [harmony-one/pump.fun.client#2]
Use connectkit or rainbow to support all major wallet. Very simply to integrate 

<img width="246" alt="image" src="https://github.com/user-attachments/assets/151bda86-992f-4f66-804b-79fbcb442f40">

**Comment by ArtemKolodko** [comment]
Added connectKit (and multiple wallets support)
https://github.com/harmony-one/pump.fun.client/commit/41d07e481698ac0b24c7c0518e37af043cba94ae

**Comment by polymorpher** [comment]
Looks good. Might need to set a custom wag config for reliable RPC. They use ankr RPC by default for some reason, and that sometimes doesn't work.

example:
https://github.com/polymorpher/otc-country/blob/f2ee7146b3db151569942407f4292cb4881f1cfd/app/src/helpers/config.ts#L19
