### ISSUE TITLE
Status and available actions are unclear for tokens that did not win competition

### ISSUE THREAD

**Issue by polymorpher** [harmony-one/pump.fun.client#3]
<img width="1308" alt="image" src="https://github.com/user-attachments/assets/020afd40-d340-4248-8f9f-e5d2cf08229b">

**Comment by polymorpher** [comment]
Still an issue in current version. Users don't know which competition round the token belongs to, who won, what currently can be done with it.

<img width="1256" alt="image" src="https://github.com/user-attachments/assets/2227a184-a887-477e-8b87-4dd864be4b57" />

**Comment by ArtemKolodko** [comment]
1) Added "Competition #" to the token header
2) For token that lost, added status and link to competition winner token
Example:
https://pump-app.netlify.app/0xe7d113a44c999d1c759deecf2c27502ccc0298c8

<img width="1373" alt="Screenshot 2024-12-12 at 2 41 57 PM" src="https://github.com/user-attachments/assets/1f1bd8b7-bfa6-4ac7-af77-bf3ec4d7f42e" />

**Comment by polymorpher** [comment]
Looks good
