### ISSUE TITLE
Current price seems to be calculated incorrectly

### ISSUE THREAD

**Issue by polymorpher** [harmony-one/pump.fun.client#8]
Related to https://github.com/harmony-one/pump.fun.client/issues/7

The box is suggesting each KOALA is worth 100 ONE. I have ~0.05 KOALA (which is also the total supply of KOALA). So the market cap  should be 5 ONE, not 0.5 ONE

<img width="368" alt="image" src="https://github.com/user-attachments/assets/c5e51b2b-425b-4a1f-9f44-29bc03575828">

**Comment by ArtemKolodko** [comment]
Fixed token price and token market cap:
https://github.com/harmony-one/pump.fun.backend/commit/374bc721905c85fc24ee70e6e09fb757a88d5b4c

**Comment by polymorpher** [comment]
Seems to work now
